rules:
  visibility:
    description: API Tags'.
    message: "should be defined values."
    severity: error
    given: $.data.tags[*]
    then:
      function: pattern
      functionOptions:
        match: "^(shack|dog|cat)$"